### ISSUE TITLE
OmegaBrowser: issues with un-ckecking boxes 

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#290] opened 2017-10-12 17:10 UTC
Inherits from  #14 #116 and #117

**Comment by strambc** [comment] 2017-10-12 17:19
See attached screen shots for a description of the problem.
In essence: 
There is a remaining issue with un-checking selection boxes when moving upstream.

# Problem 1) 
When Image 113 is un-checked 113_PD remains visible. When 33 is un-checked 113_PD disappears.

**Comment by strambc** [comment] 2017-10-12 17:19
# Problem 1) 
When Image 113 is un-checked 113_PD remains visible. When 33 is un-checked 113_PD disappears.
![issue 290_problem_1_step_1](https://user-images.githubusercontent.com/4050585/31509576-fec1e67a-af4f-11e7-92fc-93751ce9a7df.png)
![issue 290_problem_1_step_2](https://user-images.githubusercontent.com/4050585/31509577-fee1d80e-af4f-11e7-82f4-622ed08c8e6e.png)

**Comment by strambc** [comment] 2017-10-12 17:23
#Problem 2
PD gets un-checked when TM is unckecked and behavior is inverted.

![issue 290_problem_2_step_1](https://user-images.githubusercontent.com/4050585/31509732-84b0b766-af50-11e7-8882-5a8d457c28ff.png)
![issue 290_problem_2_step_2](https://user-images.githubusercontent.com/4050585/31509733-84c5e88e-af50-11e7-9881-b5fd16f82c5f.png)
![issue 290_problem_2_step_2bis](https://user-images.githubusercontent.com/4050585/31509734-84d697ec-af50-11e7-8e14-3dcbfe736722.png)
![issue 290_problem_2_step_2c](https://user-images.githubusercontent.com/4050585/31509735-84ed1346-af50-11e7-9421-670e2964e004.png)
![issue 290_problem_2_step_3](https://user-images.githubusercontent.com/4050585/31509736-8503c28a-af50-11e7-8291-4331627ef360.png)
![issue 290_problem_2_step_3bis](https://user-images.githubusercontent.com/4050585/31509737-854393ce-af50-11e7-917c-f504c8b0639a.png)
![issue 290_problem_2_step_3c](https://user-images.githubusercontent.com/4050585/31509738-8556cd2c-af50-11e7-9343-cc9a835cda48.png)
![issue 290_problem_2_step_4](https://user-images.githubusercontent.com/4050585/31509739-856c7d0c-af50-11e7-89d3-b4e9960ee801.png)

**Comment by Akramhar** [comment] 2017-10-12 17:56
Problem 1 is not a bug: checkbox on image doesn't affect PD visible or not in the column. Select (blu highlight) does affect.
Problem 2 needs to be checked.

**Comment by strambc** [comment] 2017-10-12 21:15
Problem 1 --> we have to clarify because I am not convinced about your explanation.
Problem 2 --> OK

**Comment by strambc** [comment] 2017-10-12 21:16
More problem cases 

#Problem 3

**Comment by strambc** [comment] 2017-10-12 21:54
![issue 290_problem_3_step_1](https://user-images.githubusercontent.com/4050585/31521136-65ca3248-af76-11e7-8d78-3267a3a4ee41.png)
![issue 290_problem_3_step_2](https://user-images.githubusercontent.com/4050585/31521137-65e27812-af76-11e7-846a-19f9bdfe9c68.png)
![issue 290_problem_3_step_3](https://user-images.githubusercontent.com/4050585/31521138-65f3ce78-af76-11e7-923e-748cd8fe7373.png)
![issue 290_problem_3_step_4](https://user-images.githubusercontent.com/4050585/31521139-6606a82c-af76-11e7-8770-2240f1aeb016.png)
![issue 290_problem_3_step_5](https://user-images.githubusercontent.com/4050585/31521140-661ac3c0-af76-11e7-937a-1f414d087112.png)

**Comment by Akramhar** [comment] 2017-10-13 15:49
I'm very confused by Problem 2: I'm trying to understand where is the error ("the inverted behaviour") but I don't seem to be able to understand.
Can you explain to me what is happening that is not expected?

**Comment by strambc** [comment] 2017-10-13 15:53
Surely.
Best to do it in person though.
I have tried to explain in written form as much as I can.
I think the next best thing is to talk about it in person.

On Oct 13, 2017, at 11:49, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm very confused by Problem 2: I'm trying to understand where is the error ("the inverted behaviour") but I don't seem to be able to understand.
Can you explain to me what is happening that is not expected?

**Comment by strambc** [comment] 2017-10-13 15:58
The bottom line is that when one unchecks the a box in the TM the PD gets unchecked.
This is a bug.
Then the inverted behavior happens as a consequence of that: when one clicks on the PD (which is un-checked) then the box apparently checks but the behavior is as if the box had been un-checked (because at that point the correct order of event would have been to go from checked to un-checked and not vice versa).

On Oct 13, 2017, at 11:54, Strambio, Caterina <Caterina.Strambio@umassmed.edu<mailto:Caterina.Strambio@umassmed.edu>> wrote:

Surely.
Best to do it in person though.
I have tried to explain in written form as much as I can.
I think the next best thing is to talk about it in person.

On Oct 13, 2017, at 11:49, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm very confused by Problem 2: I'm trying to understand where is the error ("the inverted behaviour") but I don't seem to be able to understand.
Can you explain to me what is happening that is not expected?

**Comment by Akramhar** [comment] 2017-10-13 16:12
ok I'll try to reproduce and see what happens

**Comment by Akramhar** [comment] 2017-10-13 16:13
Problem 3:
a) it's a limitation: the selection of what is visible on the sidebar can go only up atm, not down (from particle to track, but no from track to particle).
And since there are no segments to display, it displays the only thing available given the current selection.

**Comment by Akramhar** [comment] 2017-10-13 19:28
Problem 2 should be fixed in omega-0.36

**Comment by Akramhar** [comment] 2017-10-13 20:32
Problem 3:
b) and c) seems to be fixed in omega-0.36

**Comment by strambc** [comment] 2017-10-13 20:44
Found same issue as problem 2 happens also with Quality Control.
When one un-checks the SNR run the PD run gets unchecked as well

[cid:34705A19-8545-4F11-91D9-6381D5B5E7CF@ad.umassmed.edu][cid:76DB0DF0-2408-4038-933F-C95CEDD78150@ad.umassmed.edu]
On Oct 13, 2017, at 16:32, Akramhar <notifications@github.com<mailto:notifications@github.com>> wrote:


Problem 3:
b) and c) seems to be fixed in omega-0.36

**Comment by Akramhar** [comment] 2017-10-13 20:58
The fix should be working on that too

**Closed** 2017-10-26 22:05 UTC
Labels: bug, critical, functionality, interface
