### ISSUE TITLE
ParticleDetector and ParticleTracker MOSAIC plugins do not have "Select Image" menu

### ISSUE THREAD

**Issue by strambc** [OmegaProject/Omega#106] opened 2016-09-29 18:23 UTC
Shouldn't PD and PT have a "Select Image" menu on top like all other plugins?
Any reasons why they do not have it?

**Comment by Akramhar** [comment] 2017-01-09 22:02
PD doesn't need it because the image are already displayed in the left list, PL does have it.
If the problem is solved just close the issue :)

**Closed** 2017-04-27 22:06 UTC
Labels: enhancement, functionality, interface, medium, question
